Add dock id
open-navigation/opennav_docking pull request #46
Opened 2024-07-01 15:18 UTC by redvinaa

Add dock id feature as per #44 .

This PR adds an id field to every dock *instance* (it can be empty).

2024-07-01 16:52 UTC, SteveMacenski requested changes
Overall looks good, just some details. Can you submit this over to Nav2 as well? That way its in Jazzy and Rolling as well 

https://github.com/ros-navigation/navigation2/tree/main/nav2_docking

2024-07-01 16:52 UTC, SteveMacenski commented on opennav_docking/include/opennav_docking/utils.hpp
> +      RCLCPP_ERROR(node->get_logger(), "Dock %s has no valid 'id'.", dock_name.c_str());
Remove the error/return false, its OK if its not specified as an optional field. Otherwise will just be empty string.

2024-07-01 16:52 UTC, SteveMacenski commented on opennav_docking/src/simple_charging_dock.cpp
> +bool SimpleChargingDock::getRefinedPose(geometry_msgs::msg::PoseStamped & pose, std::string id)
```suggestion
bool SimpleChargingDock::getRefinedPose(geometry_msgs::msg::PoseStamped & pose, std::string /*id*/)
```

Then remove the `(void) id;`

2024-07-01 16:52 UTC, SteveMacenski commented on README.md
> +  id: "1"
```suggestion
  id: "kitchen_dock"
```

2024-07-01 16:52 UTC, SteveMacenski commented on README.md
> +  id: "2"
```suggestion
  id: "42"
```

2024-07-01 16:52 UTC, SteveMacenski commented on README.md
> +    id: "1"
Ditto

2024-07-01 16:53 UTC, SteveMacenski commented on README.md
> +  id: "1"
^ to show its a string and can hold string values

2024-07-02 13:22 UTC, redvinaa commented
Implemented requested changes, and opened https://github.com/ros-navigation/navigation2/pull/4511

2024-07-02 15:25 UTC, SteveMacenski approved these changes

2024-07-02 15:25 UTC, merged

2024-07-02 15:32 UTC, SteveMacenski commented
@redvinaa I had to revert it https://github.com/open-navigation/opennav_docking/pull/48. This PR does not compile.